apiVersion: v1
kind: Service
metadata:
  name: vote-canary
  labels:
    app: vote
    tier: front
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: ClusterIP
